export const ProductList = {
  chairs: {
    vitra_eames: {
      id: 1,
      glbLink: require('../assets/models/vitra_eames_chair.glb'),
      name: 'Vitra Eames',
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/vitra_eames.png'),
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: require('../assets/texture/fabric1.jpg'),
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: require('../assets/texture/fabric7.jpg'),
          varDesc: 'Two Variation',
          price: 4000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: require('../assets/texture/fabric3.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    swing_chair: {
      id: 1,
      glbLink: require('../assets/models/swing_chair.glb'),
      name: 'Swing Chair',
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/swing_chair.png'),
      variation: [
        {
          id: 'SWING001',
          name: 'One',
          thumbnail: require('../assets/texture/fabric18.jpg'),
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            wood: {
              color: '#ffffff',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric18.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SWING002',
          name: 'Two',
          thumbnail: require('../assets/texture/fabric22.png'),
          varDesc: 'Two Variation',
          price: 4000,
          varData: {
            wood: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal_ring: {
              color: '#FFDBA1',
              metalness: 0.895455,
              roughness: 0.231818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric22.png'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SWING003',
          name: 'Three',
          thumbnail: require('../assets/texture/fabric19.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            wood: {
              color: '#fffeef',
              map: require('../assets/texture/wood5.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal_ring: {
              color: '#E2E0E0',
              metalness: 0.895455,
              roughness: 0.131818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric19.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SWING004',
          name: 'Four',
          thumbnail: require('../assets/texture/fabric13.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            wood: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal_ring: {
              color: '#090909',
              metalness: 0.895455,
              roughness: 0.131818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric13.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    hanging_chair: {
      id: 1,
      glbLink: require('../assets/models/hanging_chair.glb'),
      name: 'Hanging Chair',
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/hanging_chair.png'),
      variation: [
        {
          id: 'HANGING001',
          name: 'One',
          thumbnail: require('../assets/texture/fabric20.jpg'),
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            wood: {
              color: '#ffffff',
              map: require('../assets/texture/wood5.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal: {
              color: '#292929',
              metalness: 0.0001,
              roughness: 0.129,
            },
            chain: {
              color: '#ffffff',
              metalness: 1.0,
              roughness: 0.0001,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric20.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'HANGING002',
          name: 'Two',
          thumbnail: require('../assets/texture/fabric22.png'),
          varDesc: 'Two Variation',
          price: 4000,
          varData: {
            wood: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal: {
              color: '#FFDBA1',
              metalness: 1.0,
              roughness: 0.0001,
            },
            chain: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric22.png'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'HANGING003',
          name: 'Three',
          thumbnail: require('../assets/texture/fabric19.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            wood: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal: {
              color: '#E2E0E0',
              metalness: 1.0,
              roughness: 0.1,
            },
            chain: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric19.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'HANGING004',
          name: 'Four',
          thumbnail: require('../assets/texture/fabric13.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            wood: {
              color: '#fffeef',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metal: {
              color: '#090909',
              metalness: 1.0,
              roughness: 0.0001,
            },
            chain: {
              color: '#D5DBE3',
              metalness: 1.0,
              roughness: 0.0001,
            },
            cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric13.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    ring_chair: {
      id: 1,
      glbLink: require('../assets/models/ring_chair.glb'),
      name: 'Hanging Chair',
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/ring_chair.png'),
      variation: [
        {
          id: 'RING001',
          name: 'One',
          thumbnail: require('../assets/texture/fabric10.jpg'),
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#AEAEAE',
              metalness: 1.0,
              roughness: 0.6,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric10.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'RING002',
          name: 'Two',
          thumbnail: require('../assets/texture/fabric22.png'),
          varDesc: 'Two Variation',
          price: 4000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },

            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric22.png'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'RING003',
          name: 'Three',
          thumbnail: require('../assets/texture/fabric19.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },

            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric19.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'RING004',
          name: 'Four',
          thumbnail: require('../assets/texture/fabric13.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },

            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric13.jpg'),
              metalness: 0.00001,
              roughness: 0.4,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
  sofa: {
    single_seater: {
      id: 12,
      name: 'Single Seater ',
      glbLink: require('../assets/models/single_seater.glb'),
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/single_seater.png'),
      variation: [
        {
          id: 'TAB001',
          name: 'Oak',
          thumbnail: require('../assets/texture/fabric15.jpg'),
          varDesc: 'One Variation',
          price: 6000,
          varData: {
            seat_cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric15.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
            sofa: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SOFA002',
          name: 'Oak',
          thumbnail: require('../assets/texture/fabric10.jpg'),
          varDesc: 'One Variation',
          price: 8000,
          varData: {
            seat_cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric10.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
            sofa: {
              color: '#ffffff',
              map: require('../assets/texture/fabric5.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SOFA007',
          name: 'Oak',
          thumbnail: require('../assets/texture/fabric14.jpg'),
          varDesc: 'One Variation',
          price: 7000,
          varData: {
            seat_cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric14.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
            sofa: {
              color: '#ffffff',
              map: require('../assets/texture/fabric13.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: 'SOFA00677',
          name: 'Oak',
          thumbnail: require('../assets/texture/fabric22.png'),
          varDesc: 'One Variation',
          price: 10000,
          varData: {
            seat_cushion: {
              color: '#ffffff',
              map: require('../assets/texture/fabric22.png'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
            sofa: {
              color: '#ffffff',
              map: require('../assets/texture/fabric20.jpg'),
              metalness: 0.132,
              roughness: 0.722727,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
  table: {
    round_table: {
      id: 1,
      name: 'Round Table',
      glbLink: require('../assets/models/round_table.glb'),
      desc: 'A modern take on tradition',
      thumbnail: require('../assets/texture/productThumbnail/round_table.png'),
      variation: [
        {
          id: 'TAB001',
          name: 'Oak',
          thumbnail: require('../assets/texture/wood1.jpg'),
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            round_table: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.055,
              roughness: 0.354545,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: require('../assets/texture/wood5.jpg'),
          varDesc: 'Two Variation',
          price: 4000,
          varData: {
            round_table: {
              color: '#ffffff',
              map: require('../assets/texture/wood5.jpg'),
              metalness: 0.0001,
              roughness: 0.1,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: require('../assets/texture/wood3.jpg'),
          varDesc: 'Three Variation',
          price: 3000,
          varData: {
            round_table: {
              color: '#ffffff',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.055,
              roughness: 0.354545,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
}
