export const ProductList = {
  chairs: {
    vitra_eames: {
      id: 1,
      name: 'Vitra Eames',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
  sofa: {
    vitra_eames2: {
      id: 1,
      name: 'One',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    vitra_eames5: {
      id: 1,
      name: 'Two',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
  table: {
    wrwer: {
      id: 1,
      name: 'One',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    wer: {
      id: 1,
      name: 'Two',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    asfasf: {
      id: 1,
      name: 'One',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
    sdaas: {
      id: 1,
      name: 'Two',
      desc: 'A modern take on tradition',
      thumbnail: '',
      variation: [
        {
          id: '001',
          name: 'One',
          thumbnail: '',
          varDesc: 'One Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood1.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric1.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '002',
          name: 'Two',
          thumbnail: '',
          varDesc: 'Two Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#ffffff',
              map: require('../assets/texture/wood2.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric7.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
        {
          id: '003',
          name: 'Three',
          thumbnail: '',
          varDesc: 'Three Variation',
          price: 2000,
          varData: {
            legs: {
              color: '#fffeef',
              map: require('../assets/texture/wood3.jpg'),
              metalness: 0.00001,
              roughness: 0.672727,
              repeatX: 1,
              repeatY: 1,
            },
            metals: {
              color: '#090909',
              metalness: 0.595455,
              roughness: 0.331818,
            },
            seat: {
              color: '#ffffff',
              map: require('../assets/texture/fabric3.jpg'),
              metalness: 0.00001,
              roughness: 0.825,
              repeatX: 1,
              repeatY: 1,
            },
          },
        },
      ],
    },
  },
}

const product = {
  one: {
    oneOne: {
      name: '1',
    },
    oneTwo: { name: '2' },
    oneThree: { name: '3' },
  },
  two: {
    twoOne: { name: '22' },
    twoTwo: { name: '333' },
    twoThree: { name: '4' },
  },
  three: {},
}
